research-nld: Matrix< C > Class Template Reference
Matrix< C > Class Template Reference
Class Matrix.
#include <Matrix.h>
Public Types
typedef std::vector< C > vector_type
typedef C value_type
typedef vector_type::iterator iterator
typedef vector_type::const_iterator const_iterator
typedef Base_t::reference reference
typedef Base_t::const_reference const_reference
typedef boost::call_traits
< vector_type >
::const_reference const_vector_type_reference
Public Member Functions
Matrix (size_t n_rows, size_t n_columns)
Standard Constructor.
Matrix (size_t n_rows, size_t n_columns, const value_type &value)
Assignment Constructor.
Matrix (const vector_type &v, size_t n_rows=0, size_t n_columns=0)
Conversion/data-loading constructor.
Matrix & operator= (const Matrix &other)
Assignment Operator.
size_t max_size () const
Returns the total number of elements the Matrix could possibly hold.
reference at (size_t row_idx, size_t column_idx)
Access an element, checking indices.
const_reference at (size_t row_idx, size_t column_idx) const
Access an element, checking indices.
void swap (vector_type &other)
An auxillary swap member function.
void clear (size_t n_rows=0, size_t n_columns=0)
Clear and reshape the Matrix.
void fill (value_type v, size_t n_rows=0, size_t n_columns=0)
Fill the Matrix with the specified value, and maybe resize.
void wipe (size_t n_rows=0, size_t n_columns=0)
"Erase" and possibly reshape the Matrix.
bool equivalent (const Matrix &other, double epsilon=1.0e-16) const
Check if two Matrix objects are equivalent to within some precision.
size_t nRows () const
Returns the number of rows in this MatrixAdapter.
size_t nColumns () const
Returns the number of columns in this MatrixAdapter.
void swap (MatrixAdapter &other)
The cannonical swap member function.
const_vector_type_reference as_1D () const
Returns the underlying 1-D data.
bool operator== (const MatrixAdapter &other) const
Equivalence relation.
bool operator!= (const MatrixAdapter &other) const
Returns !op==(other).
size_t size () const
Returns the total number of elements in the MatrixAdapter.
bool empty () const
Returns size() == 0.
RowProxy operator[] (size_t row_idx)
Indexes a row of the MatrixAdapter.
const RowProxy operator[] (size_t row_idx) const
Indexes a row of the MatrixAdapter.
Protected Member Functions
void reserve (size_t n_rows, size_t n_columns)
For internal use only.
Protected Attributes
size_t m__nrows
size_t m__ncols
vector_type m__data
Friends
class jpw_math::details::MatrixRef_Writer< C >
Detailed Description
template<class C>
class jpw_math::Matrix< C >
Class Matrix.
To use this class, you must also #include "details/Matrix.tcc" in the translation unit instantiating the Matrix<C> template.
N.B. - If you really need reverse iterator types for this class, typedef them yourself off of the member vector_type typedef.
Definition at line 52 of file Matrix.h.
Member Typedef Documentation
typedef vector_type::const_iterator const_iterator
Definition at line 61 of file Matrix.h.
typedef Base_t::const_reference const_reference
Reimplemented from MatrixAdapter< std::vector< C >, policy::SequenceStorage >.
Definition at line 79 of file Matrix.h.
typedef boost::call_traits<vector_type>::const_reference const_vector_type_reference [inherited]
Definition at line 141 of file MatrixAdapter.h.
typedef vector_type::iterator iterator
Definition at line 60 of file Matrix.h.
typedef Base_t::reference reference
Reimplemented from MatrixAdapter< std::vector< C >, policy::SequenceStorage >.
Definition at line 78 of file Matrix.h.
typedef C value_type
Reimplemented from MatrixAdapter< std::vector< C >, policy::SequenceStorage >.
Definition at line 59 of file Matrix.h.
typedef std::vector<C> vector_type
Reimplemented from MatrixAdapter< std::vector< C >, policy::SequenceStorage >.
Definition at line 58 of file Matrix.h.
Constructor & Destructor Documentation
Matrix (size_t n_rows, size_t n_columns)
Standard Constructor.
Equivalent to calling the same constructor in the MatrixAdapter class.
Matrix (size_t n_rows, size_t n_columns, const value_type & value)
Assignment Constructor.
Equivalent to calling the Matrix(n_rows,n_columns), then assigning value to each element.
Matrix (const vector_type & v, size_t n_rows = 0, size_t n_columns = 0) [explicit]
Conversion/data-loading constructor.
Equivalent to calling the same constructor in the MatrixAdapter class.
Member Function Documentation
const_vector_type_reference as_1D () const [inline, inherited]
Returns the underlying 1-D data.
This MatrixAdapter class organizes its elements in "typical C fashion". That is, the indices are 0-based, and the last index (the columns) vary the fastest. Element access of the form m[i][j] is, therefore, equivalent to indexing v_m[i*m.nColumns()+j] on the underlying 1-D container, v_m .
There are several instances where you will wish to or even need to access the underlying 1-D container object. You can do so here ... but only for non-modifying operations.
Definition at line 239 of file MatrixAdapter.h.
References MatrixAdapter< S, STOR_POL >::m__data.
reference at (size_t row_idx, size_t column_idx)
Access an element, checking indices.
Overloaded version for use in LHS expressions. See the documentation of the other version for behavior details.
The default implementation of this function is only valid for STL Sequences. For std::valarray, you would need to specialize this member function.
const_reference at (size_t row_idx, size_t column_idx) const
Access an element, checking indices.
Equivalent to as_1D().data()[row_idx*m.nColumns()+column_idx]. Note that the indices are all 0-based.
(The implementation of this function is only valid for STL Sequences.)
void clear (size_t n_rows = 0, size_t n_columns = 0)
Clear and reshape the Matrix.
Clear the underlying vector, then reshape the Matrix, if requested. This is equivalent to:
 oldmatrix = Matrix(n_rows, n_columns);
...but without any risk of temporary objects being constructed/destroyed. Note, however, that the internal memory backing the underlying vector is deallocated.
If you just want to "erase" the Matrix, consider calling fill() or wipe().
If either n_rows or n_columns is zero, no reshaping occurs.
bool empty () const [inline, inherited]
Returns size() == 0.
Because matrices have an intrinsic size, this function really tells you if the MatrixAdapter was default-constructed or not.
Definition at line 256 of file MatrixAdapter.h.
References MatrixAdapter< S, STOR_POL >::size().
bool equivalent (const Matrix< C > & other, double epsilon = 1.0e-16) const
Check if two Matrix objects are equivalent to within some precision.
Parameters:
other The Matrix object to compare this one to.
epsilon A small number. Each element of the two Matrix objects should differ from each other by no more than this amount.
void fill (value_type v, size_t n_rows = 0, size_t n_columns = 0)
Fill the Matrix with the specified value, and maybe resize.
Fill every element in the Matrix with v then reshape it to n_rows and n_columns if needed. If either n_rows or n_columns is zero, no reshaping occurs. Similarly, if the specified n_rows and n_columns are the same as the current dimensions, there is no resizing.
Calling this function is far more efficient than calling clear(), since the latter ultimately deallocates and reallocates the underlying memory.
To "erase" the contents of the Matrix by filling it with 0, call wipe().
Referenced by Matrix< C >::wipe().
size_t max_size () const [inline]
Returns the total number of elements the Matrix could possibly hold.
Definition at line 128 of file Matrix.h.
References MatrixAdapter< std::vector< C >, policy::SequenceStorage >::m__data.
Referenced by MatrixRef_Writer< C >::c_data().
size_t nColumns () const [inline, inherited]
Returns the number of columns in this MatrixAdapter.
Definition at line 217 of file MatrixAdapter.h.
References MatrixAdapter< S, STOR_POL >::m__ncols.
size_t nRows () const [inline, inherited]
Returns the number of rows in this MatrixAdapter.
Definition at line 214 of file MatrixAdapter.h.
References MatrixAdapter< S, STOR_POL >::m__nrows.
bool operator!= (const MatrixAdapter< std::vector< C >, policy::SequenceStorage > & other) const [inline, inherited]
Returns !op==(other).
Definition at line 245 of file MatrixAdapter.h.
References MatrixAdapter< S, STOR_POL >::operator==().
Matrix& operator= (const Matrix< C > & other)
Assignment Operator.
Equivalent to calling MatrixAdapter::operator=().
bool operator== (const MatrixAdapter< std::vector< C >, policy::SequenceStorage > & other) const [inherited]
Equivalence relation.
RowProxy operator[] (size_t row_idx) [inline, inherited]
Indexes a row of the MatrixAdapter.
This operator allows you to write expressions like:
 MatrixAdapter<vector<double> > m = some_MatrixAdapter_operation();
 m[2][7] = 3.141;
Note that the indices are all 0-based.
It returns an intermediate type that is not meant to be used directly. In fact, it's not meant to be seen at all, but (hopefully) will be optimized away by the compiler.
Definition at line 271 of file MatrixAdapter.h.
References MatrixAdapter< S, STOR_POL >::m__ncols, and MatrixAdapter< S, STOR_POL >::RowProxy.
const RowProxy operator[] (size_t row_idx) const [inline, inherited]
Indexes a row of the MatrixAdapter.
Overloaded version for accessing MatrixAdapter elements in a RHS-expression.
Please read the documentation for the other version of this function.
Definition at line 282 of file MatrixAdapter.h.
References MatrixAdapter< S, STOR_POL >::m__ncols, and MatrixAdapter< S, STOR_POL >::RowProxy.
void reserve (size_t n_rows, size_t n_columns) [protected]
For internal use only.
Referenced by MatrixRef_Writer< C >::c_data().
size_t size () const [inline, inherited]
Returns the total number of elements in the MatrixAdapter.
Definition at line 249 of file MatrixAdapter.h.
References MatrixAdapter< S, STOR_POL >::m__ncols, and MatrixAdapter< S, STOR_POL >::m__nrows.
void swap (vector_type & other)
An auxillary swap member function.
Swap the underlying vector with other. This should be way more efficient than copying in the individual elements.
other must be nRows()*nColumns() long. If not, throws a std::invalid_argument exception.
void swap (MatrixAdapter< std::vector< C >, policy::SequenceStorage > & other) [inherited]
The cannonical swap member function.
For STL Sequences and classes based on them, this should be an effcient operation. Other forms of sequence (e.g. C-style arrays and std::valarray) may not be.
void wipe (size_t n_rows = 0, size_t n_columns = 0) [inline]
"Erase" and possibly reshape the Matrix.
Equivalent to calling:
 fill(value_type(), n_rows, n_columns);
Definition at line 204 of file Matrix.h.
References Matrix< C >::fill().
Friends And Related Function Documentation
friend class jpw_math::details::MatrixRef_Writer< C > [friend]
Definition at line 55 of file Matrix.h.
Member Data Documentation
vector_type m__data [protected, inherited]
Definition at line 291 of file MatrixAdapter.h.
Referenced by Matrix< C >::max_size().
size_t m__ncols [protected, inherited]
Definition at line 290 of file MatrixAdapter.h.
size_t m__nrows [protected, inherited]
Definition at line 289 of file MatrixAdapter.h.
The documentation for this class was generated from the following file:
Matrix.h