research-nld: MatrixRef_Writer< C > Class Template Reference
MatrixRef_Writer< C > Class Template Reference
Provides a means for optimized write-access to the underlying block of memory containing the elements of a Matrix<C>.
#include <MatrixRef_Writer.h>
Public Member Functions
MatrixRef_Writer (matrix_t &m)
Default Constructor.
~MatrixRef_Writer ()
Destructor.
matrix_t * operator-> ()
Call members of the underlying Matrix object.
const matrix_t * operator-> () const
const overload of op->().
value_type * c_data (size_t row_size, size_t column_size)
Returns a pointer to the underlying data stored in the Matrix.
Detailed Description
template<class C>
class jpw_math::details::MatrixRef_Writer< C >
Provides a means for optimized write-access to the underlying block of memory containing the elements of a Matrix<C>.
Use it for cross-language or C-API support.
An illustrative example will say it all:
 extern void
 fortran_matrix_invert_(double* m, int rr, int cc);
 extern void
 legacy_C_reader(someHandle_t h, double* m, size_t nn);
 void invert_matrix(MatrixRef_Writer<double> ref_mw)
 {
     // Do some prepwork
     :
     :
     size_t nRowsNow(ref_mw->nRows())
     size_t nColsNow(ref_mw->nColumns())
     fortran_matrix_invert_(ref_mw.c_data(nRowsNow, nColsNow),
                            nRowsNow, nColsNow);
 }
 //static unsigned read_nRows ... defined elsewhere.
 //static unsigned read_nCols ... defined elsewhere.
 void readIt(MatrixRef_Writer<double> ref_mw)
 {
     // Do some prepwork, including defining and setting
     // someHandle_t rh;
     :
     :
     ref_mw->clear(read_nRows, read_nCols);
     legacy_C_reader(rh, ref_mw.c_data(read_nRows, read_nCols),
                     ref_mw->size());
     :
     :
 }
 void doExample()
 {
     // Do some prepwork
     :
     :
     Matrix<double> data;
     readIt(data);
     invert_matrix(data);
 }
As this example shows, MatrixRef_Writer<C> takes the place of a non-const Matrix<C>& arg. The function MatrixRef_Writer::c_data(), returns a pointer to the block of memory where the Matrix<C> data starts. Notice how MatrixRef_Writer::c_data() forces you to specify the underlying Matrix object's dimensions. This is by design, since your legacy API will almost certainly require you to pass the dimensions to it, too.
You can also use this class with legacy APIs that read in matrix data as a "flattened" 1-D sequence. Just be sure to resize the underlying Matrix object so that its number of rows matches the size of the slowly-varying part of the "flattened" data.
Definition at line 100 of file MatrixRef_Writer.h.
Constructor & Destructor Documentation
MatrixRef_Writer (matrix_t & m) [inline]
Default Constructor.
This is also a conversion constructor. It's designed to act as a reference-type for Matrix function args.
It stores a reference to the Matrix object, m, passed to it. Thus, m cannot go out of scope before any instances of MatrixRef_Writer do.
Definition at line 116 of file MatrixRef_Writer.h.
~MatrixRef_Writer () [inline]
Destructor.
Definition at line 121 of file MatrixRef_Writer.h.
Member Function Documentation
value_type* c_data (size_t row_size, size_t column_size) [inline]
Returns a pointer to the underlying data stored in the Matrix.
The parameters row_size and column_size specify the target layout of the data you are storing in the memory address returned.
row_size must be the "slower moving" index, i.e. c_data(rsz,csz)+i*rsz+j is the address of m[i][j] . You cannot guarantee the integrity of the underlying Matrix object otherwise.
The underlying Matrix object will be resized to fit the specified dimensions, if necessary. Consider any data in the underlying Matrix object as lost after calling this function.
Use this function only with legacy C-APIs, as per Meyers' "Effective STL", and even then, only in concert with Matrix::size() on the underlying Matrix object.
Definition at line 147 of file MatrixRef_Writer.h.
References MatrixAdapter< S, STOR_POL >::m__data, Matrix< C >::max_size(), MatrixAdapter< S, STOR_POL >::nColumns(), MatrixAdapter< S, STOR_POL >::nRows(), and Matrix< C >::reserve().
matrix_t* operator-> () [inline]
Call members of the underlying Matrix object.
Definition at line 124 of file MatrixRef_Writer.h.
const matrix_t* operator-> () const [inline]
const overload of op->().
Definition at line 127 of file MatrixRef_Writer.h.
The documentation for this class was generated from the following file:
MatrixRef_Writer.h