research-nld: MatrixAdapter< S, STOR_POL > Class Template Reference
MatrixAdapter< S, STOR_POL > Class Template Reference
Class MatrixAdapter.
#include <MatrixAdapter.h>
Classes
struct RowProxy
This is the "classic" proxy class for accessing columns of a row of a MatrixAdapter.
Public Types
typedef S vector_type
typedef traits::ContainerType
< S >::value_type value_type
typedef traits::ContainerType
< S >::reference reference
typedef traits::ContainerType
< S >::const_reference const_reference
typedef boost::call_traits
< vector_type >
::const_reference const_vector_type_reference
Public Member Functions
MatrixAdapter ()
Default Constructor.
~MatrixAdapter ()
Destructor.
MatrixAdapter (const MatrixAdapter &other)
Copy Constructor.
MatrixAdapter (size_t n_rows, size_t n_columns)
The Standard Constructor.
template<typename INPUT_ITERATOR > MatrixAdapter (INPUT_ITERATOR begin, INPUT_ITERATOR end, size_t n_rows, size_t n_columns)
Conversion/Data-Loading constructor.
MatrixAdapter & operator= (const MatrixAdapter &other)
Assignment Operator.
size_t nRows () const
Returns the number of rows in this MatrixAdapter.
size_t nColumns () const
Returns the number of columns in this MatrixAdapter.
void swap (MatrixAdapter &other)
The cannonical swap member function.
const_vector_type_reference as_1D () const
Returns the underlying 1-D data.
bool operator== (const MatrixAdapter &other) const
Equivalence relation.
bool operator!= (const MatrixAdapter &other) const
Returns !op==(other).
size_t size () const
Returns the total number of elements in the MatrixAdapter.
bool empty () const
Returns size() == 0.
RowProxy operator[] (size_t row_idx)
Indexes a row of the MatrixAdapter.
const RowProxy operator[] (size_t row_idx) const
Indexes a row of the MatrixAdapter.
Protected Attributes
size_t m__nrows
size_t m__ncols
vector_type m__data
Friends
class RowProxy
Detailed Description
template<class S, template< class > class STOR_POL = policy::SequenceStorage>
class jpw_math::MatrixAdapter< S, STOR_POL >
Class MatrixAdapter.
A Adapter class for accessing a 1-D sequence as if it were a 2-D matrix.
It is designed for efficient access, not super-flexibility. The indices are 0-based, and cannot be altered. The leading index selects the row, i.e. indexing is C-style. You cannot change it to FORTRAN style. If you need features like that, see the boost library for more powerful classes. (Those classes are, however, also more slow.)
To use this class, you must also #include "details/MatrixAdapter.tcc" in the translation unit instantiating the MatrixAdapter<...> template.
The template argument, S, can be any form of sequence class or pointer to POD type. S must, at minimum, define an operator[].
To minimize assumptions on S, there are other template arguments, for specifying policy classes.
The remaining template arguments are all policy classes.
STOR_POL describes what kind of behaviors the storage type, S, guarantees. Usually, you'll use the default, policy::SequenceStorage. Specialize this class or use it as a model if you need to "roll your own."
This class internally uses the traits::ContainerType class template to determine the data type stored in S. If you have custom requirements, specialize traits::ContainerType for your needs.
Definition at line 126 of file MatrixAdapter.h.
Member Typedef Documentation
typedef traits::ContainerType<S>::const_reference const_reference
Reimplemented in Matrix< C >.
Definition at line 139 of file MatrixAdapter.h.
typedef boost::call_traits<vector_type>::const_reference const_vector_type_reference
Definition at line 141 of file MatrixAdapter.h.
typedef traits::ContainerType<S>::reference reference
Reimplemented in Matrix< C >.
Definition at line 137 of file MatrixAdapter.h.
typedef traits::ContainerType<S>::value_type value_type
Reimplemented in Matrix< C >.
Definition at line 136 of file MatrixAdapter.h.
typedef S vector_type
Reimplemented in Matrix< C >.
Definition at line 135 of file MatrixAdapter.h.
Constructor & Destructor Documentation
MatrixAdapter ()
Default Constructor.
Creates a 0x0 matrix.
Clearly such an object is useless. Don't even think about trying to use operator[] or at() with it.
All other constructors are guaranteed to create matrix objects with nonzero dimensions. Thus, you can uniquely identify any default-constructed instances of this class.
To "insert" data into a default-constructed instance of a MatrixAdapter, you can:
Use operator=() to copy an existing MatrixAdapter into it. You don't want to do this, however:
    typedef MatrixAdapter<somesequence_t> matrix_t;
    matrix_t mt;
    :
    :
    mt = matrix_t(42, 24);
It won't perform as well as this:
Use swap() with a temporary MatrixAdapter instance. This is most useful for "copy-constructing into" the empty matrix, like so:
    typedef MatrixAdapter<somesequence_t> matrix_t;
    matrix_t mt;
    :
    :
    matrix_t nuDim_tmp(42, 24);
    mt.swap(nuDim_tmp);          // <-- Fast!
~MatrixAdapter ()
Destructor.
MatrixAdapter (const MatrixAdapter< S, STOR_POL > & other)
Copy Constructor.
MatrixAdapter (size_t n_rows, size_t n_columns)
The Standard Constructor.
Creates a matrix with the specified dimensions. The elements of the matrix will all be default-constructed.
This is the constructor you'll use most of the time.
MatrixAdapter (INPUT_ITERATOR begin, INPUT_ITERATOR end, size_t n_rows, size_t n_columns)
Conversion/Data-Loading constructor.
Creates a new matrix using the data in the sequence defined by begin and end by "reshaping" it to the specified dimensions.
The new reshaped matrix satisfies 'm[i][j] = v_m[i*m.nColumns()+j]', where v_m is the sequence bound by begin and end.
Note that this c'tor should not be used when S is a POD-pointer array type. It will fail to compile if you try to call it.
Member Function Documentation
const_vector_type_reference as_1D () const [inline]
Returns the underlying 1-D data.
This MatrixAdapter class organizes its elements in "typical C fashion". That is, the indices are 0-based, and the last index (the columns) vary the fastest. Element access of the form m[i][j] is, therefore, equivalent to indexing v_m[i*m.nColumns()+j] on the underlying 1-D container, v_m .
There are several instances where you will wish to or even need to access the underlying 1-D container object. You can do so here ... but only for non-modifying operations.
Definition at line 239 of file MatrixAdapter.h.
Referenced by jpw_math::statistics::std_dev().
bool empty () const [inline]
Returns size() == 0.
Because matrices have an intrinsic size, this function really tells you if the MatrixAdapter was default-constructed or not.
Definition at line 256 of file MatrixAdapter.h.
size_t nColumns () const [inline]
Returns the number of columns in this MatrixAdapter.
Definition at line 217 of file MatrixAdapter.h.
Referenced by MatrixRef_Writer< C >::c_data().
size_t nRows () const [inline]
Returns the number of rows in this MatrixAdapter.
Definition at line 214 of file MatrixAdapter.h.
Referenced by MatrixRef_Writer< C >::c_data().
bool operator!= (const MatrixAdapter< S, STOR_POL > & other) const [inline]
Returns !op==(other).
Definition at line 245 of file MatrixAdapter.h.
MatrixAdapter& operator= (const MatrixAdapter< S, STOR_POL > & other)
Assignment Operator.
bool operator== (const MatrixAdapter< S, STOR_POL > & other) const
Equivalence relation.
Referenced by MatrixAdapter< std::vector< C >, policy::SequenceStorage >::operator!=().
RowProxy operator[] (size_t row_idx) [inline]
Indexes a row of the MatrixAdapter.
This operator allows you to write expressions like:
 MatrixAdapter<vector<double> > m = some_MatrixAdapter_operation();
 m[2][7] = 3.141;
Note that the indices are all 0-based.
It returns an intermediate type that is not meant to be used directly. In fact, it's not meant to be seen at all, but (hopefully) will be optimized away by the compiler.
Definition at line 271 of file MatrixAdapter.h.
const RowProxy operator[] (size_t row_idx) const [inline]
Indexes a row of the MatrixAdapter.
Overloaded version for accessing MatrixAdapter elements in a RHS-expression.
Please read the documentation for the other version of this function.
Definition at line 282 of file MatrixAdapter.h.
size_t size () const [inline]
Returns the total number of elements in the MatrixAdapter.
Definition at line 249 of file MatrixAdapter.h.
Referenced by MatrixAdapter< std::vector< C >, policy::SequenceStorage >::empty().
void swap (MatrixAdapter< S, STOR_POL > & other)
The cannonical swap member function.
For STL Sequences and classes based on them, this should be an effcient operation. Other forms of sequence (e.g. C-style arrays and std::valarray) may not be.
Friends And Related Function Documentation
friend class RowProxy [friend]
Definition at line 129 of file MatrixAdapter.h.
Referenced by MatrixAdapter< std::vector< C >, policy::SequenceStorage >::operator[]().
Member Data Documentation
vector_type m__data [protected]
Definition at line 291 of file MatrixAdapter.h.
Referenced by MatrixAdapter< std::vector< C >, policy::SequenceStorage >::as_1D(), and MatrixRef_Writer< C >::c_data().
size_t m__ncols [protected]
Definition at line 290 of file MatrixAdapter.h.
Referenced by MatrixAdapter< std::vector< C >, policy::SequenceStorage >::nColumns(), MatrixAdapter< std::vector< C >, policy::SequenceStorage >::operator[](), and MatrixAdapter< std::vector< C >, policy::SequenceStorage >::size().
size_t m__nrows [protected]
Definition at line 289 of file MatrixAdapter.h.
Referenced by MatrixAdapter< std::vector< C >, policy::SequenceStorage >::nRows(), and MatrixAdapter< std::vector< C >, policy::SequenceStorage >::size().
The documentation for this class was generated from the following file:
MatrixAdapter.h