research-nld: jpw_math::statistics Namespace Reference
jpw_math::statistics Namespace Reference
Functions
void parseSeed (std::string &seedStr, unsigned &seedLo, unsigned &seedHi)
Parses a seed for the *rand48() pRNG.
void init_rand (bool verbose=true)
Seeds the *rand48() pRNG functions with the current time.
void init_rand_firstTimeOnly (bool verbose=true)
Seeds the *rand48() pRNG functions with the current time, but only if it hasn't been done already.
void init_rand (unsigned s1, unsigned s2, bool verbose=true)
Overloaded version that takes a seed as 2 unsigned integers.
index_t randidx (index_t nn)
Returns a random index from 0 to nn-1.
double range_rand (double del)
Returns a uniform random number in the range [-del,del].
double gaussrand ()
Returns a Gaussian random number with a std. deviation of 1.
double std_dev (const dvector_t &values)
Computes the standard deviation of the vector.
double std_dev (const dmatrix_t &values)
Computes the standard deviation of the cells in a Matrix.
double signif_del_chisq_tg (double &siglevel)
Returns the change in a Chi^2 distribution corresponding to the specified percent significance level.
double confidence_tg (double del_chisq_sig, const dmatrix_t &inv_curv_m, index_t parmidx, bool verbose)
Finds the confidence intervals for a least squares fit.
long nearest_multiple (double val, double nearfac, bool use_larger)
Finds the nearest multiple of a number.
Function Documentation
double jpw_math::statistics::confidence_tg (double del_chisq_sig, const dmatrix_t & inv_curv_m, index_t parmidx, bool verbose)
Finds the confidence intervals for a least squares fit.
It's only correct assuming Gaussian errors or for a linear model. Otherwise, consider it only a rough estimate.
double jpw_math::statistics::gaussrand ()
Returns a Gaussian random number with a std. deviation of 1.
void jpw_math::statistics::init_rand (bool verbose = true)
Seeds the *rand48() pRNG functions with the current time.
void jpw_math::statistics::init_rand (unsigned s1, unsigned s2, bool verbose = true)
Overloaded version that takes a seed as 2 unsigned integers.
The seed should be, at minimum, a 48-bit number.
Parameters:
s1 The upper 16 bits of the seed, stored in the first 2 bytes of s1. In other words, treat this parameter as if it's an unsigned short.
s2 The lower 32 bits of the seed.
verbose If true, print out information about the seed to stdout.
void jpw_math::statistics::init_rand_firstTimeOnly (bool verbose = true)
Seeds the *rand48() pRNG functions with the current time, but only if it hasn't been done already.
long jpw_math::statistics::nearest_multiple (double val, double nearfac, bool use_larger)
Finds the nearest multiple of a number.
use_larger indicates which multiple to return when nearfac falls exactly halfway between two multiples.
void jpw_math::statistics::parseSeed (std::string & seedStr, unsigned & seedLo, unsigned & seedHi)
Parses a seed for the *rand48() pRNG.
index_t jpw_math::statistics::randidx (index_t nn) [inline]
Returns a random index from 0 to nn-1.
Definition at line 78 of file statistics.h.
References drand48().
double jpw_math::statistics::range_rand (double del) [inline]
Returns a uniform random number in the range [-del,del].
Definition at line 84 of file statistics.h.
References drand48().
double jpw_math::statistics::signif_del_chisq_tg (double & siglevel)
Returns the change in a Chi^2 distribution corresponding to the specified percent significance level.
double jpw_math::statistics::std_dev (const dvector_t & values)
Computes the standard deviation of the vector.
Referenced by std_dev().
double jpw_math::statistics::std_dev (const dmatrix_t & values) [inline]
Computes the standard deviation of the cells in a Matrix.
Definition at line 97 of file statistics.h.
References MatrixAdapter< S, STOR_POL >::as_1D(), and std_dev().