research-nld: jpw_math Namespace Reference
jpw_math Namespace Reference
Namespaces
namespace details
namespace policy
Policy classes.
namespace statistics
namespace traits
Type Traits classes.
Classes
class Matrix
Class Matrix.
class MatrixAdapter
Class MatrixAdapter.
Typedefs
typedef std::vector< double > dvector_t
typedef Matrix< double > dmatrix_t
Functions
static const double DBL_PREC (1.0e-16)
static const double FLT_PREC (1.0e-8)
static const double TINY (1.0e-30)
static const double HUGE (1.0e30)
static const double TWOPI (2.0 *M_PI)
template<typename T > T SQR (T _a)
template<typename T > T CUBE (T _a)
template<typename T > T QUAD (T _a)
template<typename T > T MAX (T _a, T _b)
template<typename T > T MIN (T _a, T _b)
template<typename T > T ABS (T _x)
template<typename T > T MOD_1 (T _a)
template<typename T > void CHK_ABSMAX (T _v, T &_max)
template<typename T > bool NEAR_ZERO (T _x, T _a, T _b)
template<typename T > T ORDEROF (T _x)
template<typename T > bool INQUAD1 (T a)
template<typename T > bool INQUAD2 (T a)
template<typename T > bool INQUAD3 (T a)
template<typename T > bool INQUAD4 (T a)
template<typename C > C::value_type chiSquared (const C &fvec)
Compute from fvec.
template<class S , template< class > class P> std::ostream & operator<< (std::ostream &ostr, const MatrixAdapter< S, P > &m)
Typedef Documentation
typedef Matrix< double > dmatrix_t
Definition at line 244 of file Matrix.h.
typedef std::vector< double, std::allocator< double > > dvector_t
Definition at line 243 of file Matrix.h.
Function Documentation
T jpw_math::ABS (T _x) [inline]
Definition at line 77 of file MathTools.h.
C::value_type jpw_math::chiSquared (const C & fvec) [inline]
Compute from fvec.
The template parameter, C, must have minimal STL-container semantics.
NOTE: We need the typename keyword to inform the compiler that C::value_type is a member type of the template parameter, C.
Definition at line 128 of file MathTools.h.
References SQR().
void jpw_math::CHK_ABSMAX (T _v, T & _max) [inline]
Definition at line 86 of file MathTools.h.
T jpw_math::CUBE (T _a) [inline]
Definition at line 57 of file MathTools.h.
static const double jpw_math::DBL_PREC (1.0e- 16) [static]
static const double jpw_math::FLT_PREC (1.0e- 8) [static]
static const double jpw_math::HUGE (1. 0e30) [static]
bool jpw_math::INQUAD1 (T a) [inline]
Definition at line 102 of file MathTools.h.
bool jpw_math::INQUAD2 (T a) [inline]
Definition at line 107 of file MathTools.h.
bool jpw_math::INQUAD3 (T a) [inline]
Definition at line 112 of file MathTools.h.
bool jpw_math::INQUAD4 (T a) [inline]
Definition at line 116 of file MathTools.h.
References TWOPI().
T jpw_math::MAX (T _a, T _b) [inline]
Definition at line 65 of file MathTools.h.
T jpw_math::MIN (T _a, T _b) [inline]
Definition at line 70 of file MathTools.h.
T jpw_math::MOD_1 (T _a) [inline]
Definition at line 82 of file MathTools.h.
bool jpw_math::NEAR_ZERO (T _x, T _a, T _b) [inline]
Definition at line 94 of file MathTools.h.
std::ostream& jpw_math::operator<< (std::ostream & ostr, const MatrixAdapter< S, P > & m)
T jpw_math::ORDEROF (T _x) [inline]
Definition at line 98 of file MathTools.h.
T jpw_math::QUAD (T _a) [inline]
Definition at line 61 of file MathTools.h.
T jpw_math::SQR (T _a) [inline]
Definition at line 52 of file MathTools.h.
Referenced by chiSquared(), BarrierModel< F_POL_T >::deriv_h(), BarrierModel< F_POL_T >::descale_tau(), and BarrierModel< F_POL_T >::descale_width().
static const double jpw_math::TINY (1.0e- 30) [static]
static const double jpw_math::TWOPI (2.0 * M_PI) [static]
Referenced by INQUAD4().